#!/bin/bash

echo "=== PostgreSQL Backup Application ==="
echo ""
echo "1. Build the application:"
echo "   make build"
echo ""
echo "2. Configure (all settings come from the environment):"
echo "   cp .env.example .env"
echo ""
echo "3. List configured databases:"
echo "   ./pg-backup --env-file .env -list"
echo ""
echo "4. Run a one-time backup:"
echo "   ./pg-backup --env-file .env -once"
echo ""
echo "5. Run with Docker (compose reads .env automatically):"
echo "   make docker-build"
echo "   make docker-run"
echo ""
echo "6. Check health status (when running):"
echo "   curl http://localhost:8080/health"
echo "   curl http://localhost:8080/status"
echo ""
echo "7. Trigger a backup manually:"
echo "   PG_BACKUP_TRIGGER_TOKEN=... ./trigger-backup.sh"
echo ""
echo "Configuration:"
echo "- .env.example documents every variable with example values"
echo "- Standard PG* and AWS_* variables are used where they exist"
echo ""
echo "Features:"
echo "- Automatic backup scheduling with cron syntax"
echo "- Support for specific databases OR full server dump"
echo "- Auto-discovery of all databases when none specified"
echo "- Local and S3 storage options"
echo "- Compressed backup files (.sql.gz)"
echo "- Logs to stderr (visible in docker logs); optional log file"
echo "- Health check HTTP endpoints"
echo "- Docker containerization support"
echo "- CLI options for one-time backups and database listing"
echo "- Automatic retention/pruning of expired backups"
echo "- Streaming compression (flat memory use on large clusters)"
echo "- Graceful shutdown; no partial backup files left behind"
